// The ratchet files' shared shape: one writer, so every producer
// (compare.mjs --update, predict.mjs) emits byte-identical formatting and
// a re-record after a prediction diffs only where the sets differ.

import { writeFileSync } from "node:fs";
import { basename } from "node:path";

/**
 * The `just` recipe that re-records the ratchet at `path`: losses.js via
 * `wpt::update-losses`, losses-<engine>.js via `wpt::update-losses-<engine>`.
 * @param {string} path
 */
export function updateRecipe(path) {
  return `wpt::update-losses${basename(path, ".js").slice("losses".length)}`;
}

/**
 * Write the ratchet file at `path`: the standing header plus `keys`,
 * sorted.
 * @param {string} path
 * @param {string[]} keys
 */
export function writeLosses(path, keys) {
  const header = `// The WPT parity ratchet: every test the platform baseline passes that the
// round trip (shim -> WIT -> deltic -> js/deltic/websocket.ts) does not, keyed
// \`group :: test name\`. Generated by \`just ${updateRecipe(path)}\`; compare.mjs
// fails on any loss not listed here and on any listed loss no longer
// observed, so this file only changes deliberately and only shrinks as the
// shim serves more of the platform's behavior. Which kind each loss is —
// unserved or WIT-forced — is the shim header's deviations registry's to
// say (js/componentize/websocket.js).
`;
  const body = [...keys]
    .sort()
    .map((key) => `  ${JSON.stringify(key)},`)
    .join("\n");
  writeFileSync(path, `${header}export const KNOWN_LOSSES = [\n${body}\n];\n`);
}
